//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddEmployee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID_Employee_RK { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> ID_Competence_FK { get; set; }
        public Nullable<int> ID_WorkShift_FK { get; set; }
    
        public virtual Competence Competence { get; set; }
        public virtual WorkShift WorkShift { get; set; }
    }
}
